service: vision-client
runtime: custom
env: flex
instance_class: F2

# GCP Config
env_variables:
  PROJECT_ID: wildlife-247309
  BUCKET_NAME: bucket03y
  REGION: europe-west1
  OAUTH2_CLIENT_ID: 607867440081-2v0agkktnu5v02cl912lmg46opibi76q.apps.googleusercontent.com
  OAUTH2_CLIENT_SECRET: mqTfCGJVLjTp4ZJtFd0_4cvL
  OAUTH2_CALLBACK: https://vision-client-dot-wildlife-247309.appspot.com/auth/google/callback
  GOOGLE_APPLICATION_CREDENTIALS: ./key_account/wildlife-d61cd2da89d3.json